### ISSUE TITLE
Page refresh after clicking the upload button

### ISSUE THREAD

**Issue by kneth95** [wab/ninja-forms-uploads#3]
Hi guys,

I'm wondering how to fix this issues.

So i've already installed the file upload plugin and i've been trying to use it, but there's some problem i have to face. Everytime i click the file upload button, it keeps refreshing the page, and the whole form reset, plus the file still not uploaded.

I hope i explained it clearly. Please let me know if someone have the solution.

Thanks,
Regard.
![error](https://user-images.githubusercontent.com/14278906/39465362-2e6a58d0-4d4d-11e8-89ab-5505217b9137.JPG)

**Comment by wallsmetalroofing** [comment]
I just came across this issue as well. On clicking the file upload button in redirects to my homepage

**Comment by deDwarf** [comment]
Hi,
This might be a part of "includes/templates/fields-file-upload.html" template what is causing this:
```
<button class="btn btn-success nf-fu-fileinput-button">
        <span>{{{ nf_upload.strings.select_files }}}</span>
</button>
```

It looks like "submit" type is implicitly assigned to that "upload" button, resulting refreshes every time one clicks it. I believe changing this type to "button" should resolve the problem.

@wab could you please have a look at that? I`d try it by myself, but I don`t have a possibility to test it, unfortunately

**Comment by swartjie** [comment]
Hey deDwarf, Sure i'd be happy to test it. Can you confirm...

My Button looks like this:
<script id="tmpl-nf-field-file-upload" type="text/template">
	<button class="btn btn-success nf-fu-fileinput-button">
        <span>{{{ nf_upload.strings.select_files }}}</span>
    </button>
	<input class="nf-element" style="display: block; visibility: hidden; width: 0; height: 0;" type="file" <# data.uploadMulti ? print( 'name="files[]" multiple' ) : print ( 'name="files"' ) #>>
	<input type="hidden" class="nf-upload-nonce" value="{{{ data.uploadNonce }}}">
	<div class="nf-fu-progress">
		<div class="nf-fu-progress-bar nf-fu-progress-bar-success animate"></div>
	</div>
	<div class="files_uploaded"></div>
</script>

I just want to be sure I am not bugging everything up. How would you recommend we change it?

**Comment by kneth95** [comment]
hi guys it is now solved.
download the files here: https://github.com/wpninjas/ninja-forms-uploads

**Comment by jas8522** [comment]
This is still an issue in the live version of the plugin... shouldn't this be fixed / updated? It has been three months...
